name:  tapo_calendar
version: 0.0.1
author: Herbert Poul <herbert.poul@gmail.com>
description:  A simple day-view calendar implementation for polymer.

dependencies:
  polymer: any
#  js: any
#  unittest: any
  quiver: 0.10.0
  logging: any
