name: tapo_calendar
author: Herbert Poul <h.poul@tapo.at>
version: 0.0.3-dev.1
homepage: https://github.com/hpoul/tapo-calendar
description: A simple day-view calendar implementation for polymer.
dependencies:
  logging: '>=0.9.1 <1.0.0'
  polymer: '>=0.9.3 <1.0.0'
  quiver: 0.10.0
transformers:
- polymer:
    entry_points: []
